spring.application.name=samplePJ
# 1. 接続先のデータベースの場所（URL）
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_app

# 2. データベースのユーザー名（デフォルトは postgres）
spring.datasource.username=postgres

# 3. pgAdminにログインするときのパスワード
spring.datasource.password=${DB_PASSWORD:}

# 4. データベースのドライバー（PostgreSQL用）
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath:com/example/demo/*.xml
#mybatis.configuration.map-underscore-to-camel-case=true
