spring.application.name=samplePJ
# 1. 接続先のデータベースの場所（URL）
spring.datasource.url=jdbc:postgresql://localhost:5432/todo_app

# 2. データベースのユーザー名（デフォルトは postgres）
spring.datasource.username=${DB_USER:todo_app}

# 3. pgAdminにログインするときのパスワード
spring.datasource.password=${DB_PASSWORD}

# 4. データベースのドライバー（PostgreSQL用）
spring.datasource.driver-class-name=org.postgresql.Driver

mybatis.mapper-locations=classpath:com/example/demo/*.xml
#mybatis.configuration.map-underscore-to-camel-case=true
spring.sql.init.mode=never
spring.datasource.continue-on-error=false
#SQL初期化スクリプトでエラーが起きたときに、無視して起動を続けさせるか、それとも起動自体を失敗させて気づけるようにするか」という設定です。false(今の値)は「エラーが起きたら起動を失敗させる」という意味で、これはschema.sqlに間違いがあったときに気づきやすくなるので、むしろ残しておくことをお勧めします。